<?php

namespace Database\Seeders;

use App\Models\Ebook;
use Illuminate\Database\Seeder;

class VisibleCatalogEbookSeeder extends Seeder
{
    public function run(): void
    {
        $ebooks = [
            [
                'slug' => 'laut-bercerita',
                'title' => 'Laut Bercerita',
                'description' => 'Laut Bercerita adalah novel yang mengisahkan perjuangan, kehilangan, dan harapan di masa penuh gejolak.',
                'author' => 'Leila S. Chudori',
                'price' => 59000,
                'category' => 'Novel',
                'cover_image' => 'laut-bercerita.jpeg',
            ],
            [
                'slug' => 'atomic-habits',
                'title' => 'Atomic Habits',
                'description' => 'Atomic Habits menjelaskan bagaimana perubahan kecil yang konsisten dapat membentuk hasil besar.',
                'author' => 'James Clear',
                'price' => 0,
                'category' => 'Pengembangan Diri',
                'cover_image' => 'https://images-na.ssl-images-amazon.com/images/I/91bYsX41DVL.jpg',
            ],
            [
                'slug' => 'sapiens',
                'title' => 'Sapiens',
                'description' => 'Sapiens membahas evolusi manusia dari masa purba hingga modern.',
                'author' => 'Yuval Noah Harari',
                'price' => 135000,
                'category' => 'Sejarah',
                'cover_image' => 'https://images-na.ssl-images-amazon.com/images/I/713jIoMO3UL.jpg',
            ],
            [
                'slug' => 'psychology-of-money',
                'title' => 'Psychology of Money',
                'description' => 'Psychology of Money mengeksplorasi bagaimana orang berpikir tentang uang.',
                'author' => 'Morgan Housel',
                'price' => 0,
                'category' => 'Bisnis',
                'cover_image' => 'https://images-na.ssl-images-amazon.com/images/I/71g2ednj0JL.jpg',
            ],
            [
                'slug' => 'clean-code',
                'title' => 'Clean Code',
                'description' => 'Clean Code adalah panduan praktis untuk menulis kode yang bersih dan mudah dipelihara.',
                'author' => 'Robert C. Martin',
                'price' => 120000,
                'category' => 'Teknologi',
                'cover_image' => 'https://images-na.ssl-images-amazon.com/images/I/41SH-SvWPxL.jpg',
            ],
            [
                'slug' => 'mindset',
                'title' => 'Mindset',
                'description' => 'Mindset menjelaskan perbedaan antara fixed mindset dan growth mindset.',
                'author' => 'Carol S. Dweck',
                'price' => 0,
                'category' => 'Pengembangan Diri',
                'cover_image' => 'mindset.jpeg',
            ],
            [
                'slug' => 'dune',
                'title' => 'Dune',
                'description' => 'Kisah epik di gurun Arrakis tentang kekuasaan, takdir, dan perebutan rempah.',
                'author' => 'Frank Herbert',
                'price' => 118000,
                'category' => 'Sci-Fi',
                'cover_image' => 'https://images-na.ssl-images-amazon.com/images/I/91uwocAMtSL.jpg',
            ],
            [
                'slug' => 'the-alchemist',
                'title' => 'The Alchemist',
                'description' => 'Novel reflektif tentang keberanian mengikuti mimpi dan menemukan tujuan pribadi.',
                'author' => 'Paulo Coelho',
                'price' => 84000,
                'category' => 'Fiksi',
                'cover_image' => 'https://images-na.ssl-images-amazon.com/images/I/71aFt4+OTOL.jpg',
            ],
            [
                'slug' => 'midnight-library',
                'title' => 'The Midnight Library',
                'description' => 'Kisah emosional tentang kemungkinan hidup yang berbeda, penyesalan, dan harapan.',
                'author' => 'Matt Haig',
                'price' => 92000,
                'category' => 'Fiksi',
                'cover_image' => 'https://images-na.ssl-images-amazon.com/images/I/81J6APjwxlL.jpg',
            ],
            [
                'slug' => 'ikigai',
                'title' => 'Ikigai',
                'description' => 'Rahasia hidup panjang dan bahagia dari Jepang melalui tujuan dan kebiasaan kecil.',
                'author' => 'Hector Garcia',
                'price' => 88000,
                'category' => 'Pengembangan Diri',
                'cover_image' => 'https://images-na.ssl-images-amazon.com/images/I/81l3rZK4lnL.jpg',
            ],
            [
                'slug' => 'norwegian-wood',
                'title' => 'Norwegian Wood',
                'description' => 'Novel tentang memori, kehilangan, dan masa muda.',
                'author' => 'Haruki Murakami',
                'price' => 89000,
                'category' => 'Fiksi',
                'cover_image' => 'https://covers.openlibrary.org/b/isbn/9780375704024-L.jpg',
            ],
            [
                'slug' => 'pulang',
                'title' => 'Pulang',
                'description' => 'Kisah keluarga, perjalanan, dan pulang pada makna hidup.',
                'author' => 'Tere Liye',
                'price' => 49000,
                'category' => 'Seri Novel',
                'cover_image' => 'https://covers.openlibrary.org/b/isbn/9786020822129-L.jpg',
            ],
            [
                'slug' => 'bumi',
                'title' => 'Bumi',
                'description' => 'Awal petualangan fantasi dalam dunia paralel.',
                'author' => 'Tere Liye',
                'price' => 49000,
                'category' => 'Seri Novel',
                'cover_image' => 'https://covers.openlibrary.org/b/isbn/9786020332956-L.jpg',
            ],
            [
                'slug' => 'rich-dad-poor-dad',
                'title' => 'Rich Dad Poor Dad',
                'description' => 'Pelajaran dasar tentang aset, uang, dan cara berpikir finansial.',
                'author' => 'Robert T. Kiyosaki',
                'price' => 79000,
                'category' => 'Ekonomi',
                'cover_image' => 'https://covers.openlibrary.org/b/isbn/9781612680194-L.jpg',
            ],
            [
                'slug' => 'thinking-fast-slow',
                'title' => 'Thinking, Fast and Slow',
                'description' => 'Cara kerja pikiran manusia dalam mengambil keputusan.',
                'author' => 'Daniel Kahneman',
                'price' => 110000,
                'category' => 'Self Dev',
                'cover_image' => 'https://covers.openlibrary.org/b/isbn/9780374533557-L.jpg',
            ],
            [
                'slug' => 'deep-work',
                'title' => 'Deep Work',
                'description' => 'Panduan fokus mendalam di tengah distraksi digital.',
                'author' => 'Cal Newport',
                'price' => 85000,
                'category' => 'Motivasi',
                'cover_image' => 'https://covers.openlibrary.org/b/isbn/9781455586691-L.jpg',
            ],
            [
                'slug' => 'start-with-why',
                'title' => 'Start With Why',
                'description' => 'Mengapa tujuan yang jelas membuat organisasi lebih kuat.',
                'author' => 'Simon Sinek',
                'price' => 88000,
                'category' => 'Motivasi',
                'cover_image' => 'https://covers.openlibrary.org/b/isbn/9781591846444-L.jpg',
            ],
            [
                'slug' => 'zero-to-one',
                'title' => 'Zero to One',
                'description' => 'Cara membangun perusahaan dan produk yang benar-benar baru.',
                'author' => 'Peter Thiel',
                'price' => 82000,
                'category' => 'Bisnis',
                'cover_image' => 'https://covers.openlibrary.org/b/isbn/9780804139298-L.jpg',
            ],
            [
                'slug' => 'good-to-great',
                'title' => 'Good to Great',
                'description' => 'Riset tentang perusahaan yang berubah dari baik menjadi hebat.',
                'author' => 'Jim Collins',
                'price' => 98000,
                'category' => 'Bisnis',
                'cover_image' => 'https://covers.openlibrary.org/b/isbn/9780066620992-L.jpg',
            ],
            [
                'slug' => 'the-lean-startup',
                'title' => 'The Lean Startup',
                'description' => 'Metode membangun bisnis dengan eksperimen cepat.',
                'author' => 'Eric Ries',
                'price' => 92000,
                'category' => 'Bisnis',
                'cover_image' => 'https://covers.openlibrary.org/b/isbn/9780307887894-L.jpg',
            ],
            [
                'slug' => 'economics-in-one-lesson',
                'title' => 'Economics in One Lesson',
                'description' => 'Pengantar ekonomi klasik yang ringkas dan tajam.',
                'author' => 'Henry Hazlitt',
                'price' => 75000,
                'category' => 'Ekonomi',
                'cover_image' => 'https://covers.openlibrary.org/b/isbn/9780517548233-L.jpg',
            ],
            [
                'slug' => 'freakonomics',
                'title' => 'Freakonomics',
                'description' => 'Melihat ekonomi dari sudut pandang yang tidak biasa.',
                'author' => 'Steven D. Levitt',
                'price' => 86000,
                'category' => 'Ekonomi',
                'cover_image' => 'https://covers.openlibrary.org/b/isbn/9780060731335-L.jpg',
            ],
            [
                'slug' => 'capital-in-21st-century',
                'title' => 'Capital in the Twenty-First Century',
                'description' => 'Kajian ketimpangan dan kapital dalam ekonomi modern.',
                'author' => 'Thomas Piketty',
                'price' => 145000,
                'category' => 'Ekonomi',
                'cover_image' => 'https://covers.openlibrary.org/b/isbn/9780674430006-L.jpg',
            ],
            [
                'slug' => 'clean-architecture',
                'title' => 'Clean Architecture',
                'description' => 'Prinsip arsitektur perangkat lunak yang tahan perubahan.',
                'author' => 'Robert C. Martin',
                'price' => 125000,
                'category' => 'Teknologi',
                'cover_image' => 'https://covers.openlibrary.org/b/isbn/9780134494166-L.jpg',
            ],
            [
                'slug' => 'javascript-good-parts',
                'title' => 'JavaScript: The Good Parts',
                'description' => 'Bagian terbaik JavaScript untuk menulis kode yang lebih baik.',
                'author' => 'Douglas Crockford',
                'price' => 99000,
                'category' => 'Teknologi',
                'cover_image' => 'https://covers.openlibrary.org/b/isbn/9780596517748-L.jpg',
            ],
            [
                'slug' => 'python-crash-course',
                'title' => 'Python Crash Course',
                'description' => 'Pengantar Python praktis dengan proyek nyata.',
                'author' => 'Eric Matthes',
                'price' => 115000,
                'category' => 'Teknologi',
                'cover_image' => 'https://covers.openlibrary.org/b/isbn/9781593279288-L.jpg',
            ],
            [
                'slug' => 'design-patterns',
                'title' => 'Design Patterns',
                'description' => 'Pola desain klasik untuk software berorientasi objek.',
                'author' => 'Erich Gamma et al.',
                'price' => 135000,
                'category' => 'Teknologi',
                'cover_image' => 'https://covers.openlibrary.org/b/isbn/9780201633610-L.jpg',
            ],
            [
                'slug' => 'breath',
                'title' => 'Breath',
                'description' => 'Sains dan praktik bernapas untuk kesehatan.',
                'author' => 'James Nestor',
                'price' => 88000,
                'category' => 'Kesehatan',
                'cover_image' => 'https://covers.openlibrary.org/b/isbn/9780735213616-L.jpg',
            ],
            [
                'slug' => 'why-we-sleep',
                'title' => 'Why We Sleep',
                'description' => 'Mengapa tidur penting untuk tubuh dan pikiran.',
                'author' => 'Matthew Walker',
                'price' => 96000,
                'category' => 'Kesehatan',
                'cover_image' => 'https://covers.openlibrary.org/b/isbn/9781501144318-L.jpg',
            ],
            [
                'slug' => 'the-body-keeps-score',
                'title' => 'The Body Keeps the Score',
                'description' => 'Hubungan trauma, tubuh, dan proses pemulihan.',
                'author' => 'Bessel van der Kolk',
                'price' => 105000,
                'category' => 'Kesehatan',
                'cover_image' => 'https://covers.openlibrary.org/b/isbn/9780143127741-L.jpg',
            ],
            [
                'slug' => 'outlive',
                'title' => 'Outlive',
                'description' => 'Strategi hidup panjang dan sehat berbasis sains.',
                'author' => 'Peter Attia',
                'price' => 132000,
                'category' => 'Kesehatan',
                'cover_image' => 'https://covers.openlibrary.org/b/isbn/9780593236598-L.jpg',
            ],
        ];

        foreach ($ebooks as $ebook) {
            Ebook::updateOrCreate(
                ['slug' => $ebook['slug']],
                $ebook + ['status' => 'published']
            );
        }
    }
}
